# Generated by Django 6.1 on 2026-08-27 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_branch', to='accounts.departments')),
            ],
        ),
    ]
