# Generated by Django 6.1 on 2026-09-11 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contact'),
        ('exams', '0002_semester_syllabus_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_note', to='accounts.departments')),
                ('semseter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_notes', to='exams.semester')),
            ],
        ),
    ]
